[ncheneweth] port from feedyard

diff --git a/src/commands/confirm-registry.yaml b/src/commands/confirm-registry.yaml
--- a/src/commands/confirm-registry.yaml
+++ b/src/commands/confirm-registry.yaml
@@ -1,6 +1,8 @@
 # src/commands/confirm-registry.yaml
 
-description: validate docker registry credentials
+description: |
+  confirm $DOCKER_LOGIN and $DOCKER_PASSWORD environment variables are set and
+  run docker login to ensure that you can push the build image
 
 parameters:
 
@@ -9,68 +11,54 @@ parameters:
     type: string
     default: docker.io
 
-  image:
-    description: Name of image
-    type: string
-    default: ""
-
-  docker-login:
+  registry-login:
     description: username for reigstry access
     type: env_var_name
     default: DOCKER_LOGIN
 
-  docker-password:
+  registry-password:
     description: password for registry access
     type: env_var_name
     default: DOCKER_PASSWORD
 
-  aws-ecr:
-    description: Use aws ecr
-    type: boolean
-    default: false
-
-  aws-role:
-    description: Assume aws role as part of authentication
-    type: string
-    default: ""
-
-  aws-access-key-id:
-    description: password for registry access
-    type: env_var_name
-    default: AWS_ACCESS_KEY_ID
-
-  aws-secret-access-key:
-    description: password for registry access
-    type: env_var_name
-    default: AWS_SECRET_ACCESS_KEY
-
-  aws-region:
-    description: AWS region used for aws credentials
-    type: string
-    default: $AWS_DEFAULT_REGION
-
 steps:
-  - unless:
-      condition: << parameters.aws-ecr >>
-      name: Confirm Docker registry credentials are available and valid
-      steps:
-        - run:
-            environment:
-              REGISTRY: << parameters.registry >>
-              DOCKER_LOGIN: << parameters.docker-login >>
-              DOCKER_PASSWORD: << parameters.docker-password >>
-            command: << include(scripts/confirm-registry.sh) >>
-  - when:
-      condition: << parameters.aws-ecr >>
-      name: Confirm aws ecr credentials are available and valid
-      steps:
-        - run:
-            environment:
-              AWS_ECR: << parameters.aws-ecr >>
-              AWS_ROLE: << parameters.aws-role >>
-              REGISTRY: << parameters.registry >>
-              IMAGE: << parameters.image >>
-              AWS_ACCESS_KEY_ID: << parameters.aws-access-key-id >>
-              AWS_SECRET_ACCESS_KEY: << parameters.aws-secret-access-key >>
-              AWS_DEFAULT_REGION: << parameters.aws-region >>
-            command: << include(scripts/confirm-registry.sh) >>
+  - run:
+      name: Confirm Docker registry environment variables are configured and correct
+      command: |
+        if [ ! ${<< parameters.registry-login >>-} ]; then
+          echo "registry access username is not set, will not be able to push image."
+          exit 1
+        fi
+
+        if [ ! ${<< parameters.registry-password >>-} ]; then
+          echo "registry access password is not set, will not be able to push image."
+          exit 1
+        fi
+  - run:
+      name: Confirm Docker registry login
+      command: |
+        echo 'write to .docker/config.json is secure in ephemeral runtime environment'
+        echo ${<< parameters.registry-password >>} | docker login -u ${<< parameters.registry-login >>} --password-stdin << parameters.registry >>
+  # - when:
+  #     name: Using AWS Elastic Container Registry
+  #     condition: << parameters.assume-aws-role >>
+  #     steps:
+  #       - run:
+  #           name: Assume AWS role and obtain ecr get-login-password
+  #           command: |
+  #             aws sts assume-role --output json --role-arn << parameters.assume-aws-role >> --role-session-name "circleci executor -build pipeline" > .temp_credentials || { echo 'sts failure!' ; exit 1; }
+
+  #             ACCESS_KEY=$(cat .temp_credentials | jq -r ".Credentials.AccessKeyId")
+  #             SECRET_KEY=$(cat .temp_credentials | jq -r ".Credentials.SecretAccessKey")
+  #             SESSION_TOKEN=$(cat .temp_credentials | jq -r ".Credentials.SessionToken")
+  #             EXPIRATION=$(cat .temp_credentials | jq -r ".Credentials.Expiration")
+
+  #             cat \<<EOF > ~/.aws/credentials
+  #             [default]
+  #             aws_access_key_id=${ACCESS_KEY}
+  #             aws_secret_access_key=${SECRET_KEY}
+  #             aws_session_token=${SESSION_TOKEN}
+  #             region=<< parameters.aws-default-region >>
+  #             EOF
+
+  #             aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin << parameters.aws-image-repository >>
