[ncheneweth] debug aws ecr functionality

diff --git a/src/commands/confirm-registry.yaml b/src/commands/confirm-registry.yaml
--- a/src/commands/confirm-registry.yaml
+++ b/src/commands/confirm-registry.yaml
@@ -51,7 +51,7 @@ steps:
               region=${AWS_DEFAULT_REGION}
               EOF
               if [[ ! -z "$AWS_ASSUME_ROLE" ]]; then
-                aws sts assume-role --output json --role-arn $AWS_ASSUME_ROLE --role-session-name "circleci executor -build pipeline" > .temp_credentials || { echo 'sts failure!' ; exit 1; }
+                aws sts assume-role --output json --role-arn $AWS_ASSUME_ROLE --role-session-name "circleci-executor-build-pipeline" > .temp_credentials || { echo 'sts failure!' ; exit 1; }
 
                 ACCESS_KEY=$(cat .temp_credentials | jq -r ".Credentials.AccessKeyId")
                 SECRET_KEY=$(cat .temp_credentials | jq -r ".Credentials.SecretAccessKey")
