[ncheneweth] push.yaml and tests

diff --git a/src/commands/push.yaml b/src/commands/push.yaml
--- a/src/commands/push.yaml
+++ b/src/commands/push.yaml
@@ -16,7 +16,7 @@ parameters:
   tag:
     description: Value for tag
     type: string
-    default: ${CIRCLE_SHA1:0:7}
+    default: $CIRCLE_SHA1
 
   docker-login:
     description: username for reigstry access
@@ -51,7 +51,7 @@ parameters:
   aws-region:
     description: AWS region used for aws credentials
     type: string
-    default: ${AWS_DEFAULT_REGION}
+    default: $AWS_DEFAULT_REGION
 
 steps:
   - unless:
@@ -67,12 +67,22 @@ steps:
       name: Publish a tagged image to the aws ecr registry
       steps:
         - run:
-            environment:
-              AWS_ROLE: << parameters.aws-role >>
-              AWS_ACCESS_KEY_ID: << parameters.aws-access-key-id >>
-              AWS_SECRET_ACCESS_KEY: << parameters.aws-secret-access-key >>
-              AWS_DEFAULT_REGION: << parameters.aws-region >>
-              REGISTRY: << parameters.registry >>
-              IMAGE: << parameters.image >>
-              TAG: << parameters.tag >>
-            command: << include(scripts/aws-push.sh) >>
+            command: |
+              if [ "<< parameters.aws-role >>" ]; then
+                TMP="$(aws sts assume-role --output json --role-arn << parameters.aws-role >> --role-session-name 'orb-executor-tools-pipeline' || { echo 'sts failure!' ; exit 1; })"
+                export AWS_ACCESS_KEY_ID=$(echo $TMP | jq -r ".Credentials.AccessKeyId")
+                export AWS_SECRET_ACCESS_KEY=$(echo $TMP | jq -r ".Credentials.SecretAccessKey")
+                export AWS_SESSION_TOKEN=$(echo $TMP | jq -r ".Credentials.SessionToken")
+              fi
+              aws ecr get-login-password --region << parameters.aws-region >> | docker login --username AWS --password-stdin "<< parameters.registry >>/<< parameters.image >>"
+              docker push << parameters.registry >>/<< parameters.image >>:<< parameters.tag >>
+        # - run:
+        #     environment:
+        #       AWS_ROLE: << parameters.aws-role >>
+        #       AWS_ACCESS_KEY_ID: << parameters.aws-access-key-id >>
+        #       AWS_SECRET_ACCESS_KEY: << parameters.aws-secret-access-key >>
+        #       AWS_DEFAULT_REGION: << parameters.aws-region >>
+        #       REGISTRY: << parameters.registry >>
+        #       IMAGE: << parameters.image >>
+        #       TAG: << parameters.tag >>
+        #     command: << include(scripts/aws-push.sh) >>
